### ISSUE TITLE
Annouce PMD update (Apex and Code Climate improvements)

### ISSUE THREAD

**Issue by rsoesemann** [sivakumar-kailasam/codeclimate-pmd#6]
Hy @sivakumar-kailasam,

is your engine already running? If so very cool. We're still struggling with Java-stuff....

We added many improvements to PMD in the last pull request (https://github.com/pmd/pmd/pull/87). This is to just to tell you that this engines users might profit from updating your engine.

After you update the engine I would love to test out your engine on one of our public Apex repos https://github.com/Up2Go/visualforce-table-grid. I saw that you exclude the Apex rules, did I do the config right in https://github.com/Up2Go/visualforce-table-grid/blob/master/.codeclimate.yml?

**Comment by sivakumar-kailasam** [comment]
It's working now. I'm testing it with different repos now. If you check the PMD repo, you'd notice that they're yet to make a release since December. I don't want to upgrade to unreleased code. Also my top priority right now is to get this engine into beta. I'm doing this in my spare time, so can't commit on timelines but soon enough 😄
